import jsPDF from 'jspdf';
import type { PlatformOutput, Platform } from '@/types';

const PLATFORM_LABELS: Record<Platform, string> = {
  twitter: 'Twitter/X',
  linkedin: 'LinkedIn',
  reddit: 'Reddit',
  substack: 'Substack Notes',
};

const PLATFORM_COLORS: Record<Platform, string> = {
  twitter: '#1DA1F2',
  linkedin: '#0A66C2',
  reddit: '#FF4500',
  substack: '#FF6719',
};

export async function generatePDF(
  outputs: Record<Platform, PlatformOutput | null>,
  title: string
): Promise<void> {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  pdf.setFillColor(24, 24, 24);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');

  pdf.setTextColor(207, 207, 207);
  pdf.setFontSize(28);
  pdf.text('ContentSeed', pageWidth / 2, 50, { align: 'center' });

  pdf.setFontSize(14);
  pdf.text('Generated Content Export', pageWidth / 2, 65, { align: 'center' });

  if (title) {
    pdf.setFontSize(12);
    pdf.setTextColor(160, 160, 160);
    pdf.text(title, pageWidth / 2, 80, { align: 'center' });
  }

  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  pdf.setFontSize(10);
  pdf.text(date, pageWidth / 2, 90, { align: 'center' });

  let yPosition = 110;

  const platforms: Platform[] = ['twitter', 'linkedin', 'reddit', 'substack'];

  for (const platform of platforms) {
    const output = outputs[platform];
    if (!output) continue;

    if (yPosition > pageHeight - 60) {
      pdf.addPage();
      pdf.setFillColor(24, 24, 24);
      pdf.rect(0, 0, pageWidth, pageHeight, 'F');
      yPosition = 20;
    }

    const hexColor = PLATFORM_COLORS[platform];
    const r = parseInt(hexColor.slice(1, 3), 16);
    const g = parseInt(hexColor.slice(3, 5), 16);
    const b = parseInt(hexColor.slice(5, 7), 16);
    pdf.setFillColor(r, g, b);
    pdf.roundedRect(margin, yPosition, contentWidth, 8, 2, 2, 'F');

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text(PLATFORM_LABELS[platform], margin + 4, yPosition + 5.5);

    yPosition += 15;

    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(180, 180, 180);
    pdf.setFontSize(10);

    const contentLines = pdf.splitTextToSize(output.content, contentWidth - 4);
    
    for (const line of contentLines) {
      if (yPosition > pageHeight - 30) {
        pdf.addPage();
        pdf.setFillColor(24, 24, 24);
        pdf.rect(0, 0, pageWidth, pageHeight, 'F');
        yPosition = 20;
      }
      pdf.text(line, margin + 4, yPosition);
      yPosition += 5;
    }

    if (output.hashtags.length > 0) {
      yPosition += 3;
      pdf.setTextColor(100, 100, 100);
      pdf.setFontSize(9);
      const hashtagText = output.hashtags.join(' ');
      const hashtagLines = pdf.splitTextToSize(hashtagText, contentWidth - 4);
      for (const line of hashtagLines) {
        pdf.text(line, margin + 4, yPosition);
        yPosition += 4;
      }
    }

    yPosition += 10;
  }

  pdf.setTextColor(80, 80, 80);
  pdf.setFontSize(8);
  pdf.text('Generated by ContentSeed', pageWidth / 2, pageHeight - 10, { align: 'center' });

  const timestamp = new Date().toISOString().split('T')[0];
  pdf.save(`contentseed-export-${timestamp}.pdf`);
}
