import { Twitter, Linkedin, MessageCircle, Mail, Sprout } from 'lucide-react';
import type { Platform, PlatformOutput } from '@/types';
import { themeConfig } from '@/lib/export/theme-config';

const PLATFORM_LABELS: Record<Platform, string> = {
  twitter: 'Twitter/X',
  linkedin: 'LinkedIn',
  reddit: 'Reddit',
  substack: 'Substack Notes',
};

const PLATFORM_ICONS: Record<Platform, typeof Twitter> = {
  twitter: Twitter,
  linkedin: Linkedin,
  reddit: MessageCircle,
  substack: Mail,
};

const PLATFORM_COLORS: Record<Platform, string> = {
  twitter: '#1DA1F2',
  linkedin: '#0A66C2',
  reddit: '#FF4500',
  substack: '#FF6719',
};

interface ExportCardProps {
  output: PlatformOutput;
  className?: string;
}

export function ExportCard({ output, className }: ExportCardProps) {
  const Icon = PLATFORM_ICONS[output.platform];
  const platformColor = PLATFORM_COLORS[output.platform];

  const isThread = output.platform === 'twitter' && output.content.includes('\n\n');
  const tweets = isThread
    ? output.content.split('\n\n').filter((t) => t.trim())
    : [output.content];

  return (
    <div
      className={className}
      style={{
        backgroundColor: themeConfig.dark.background,
        borderRadius: themeConfig.borderRadius,
        padding: '24px',
        width: '100%',
        maxWidth: '500px',
        fontFamily: themeConfig.fonts.sans,
        color: themeConfig.dark.foreground,
      }}
    >
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          marginBottom: '16px',
          paddingBottom: '12px',
          borderBottom: `1px solid ${themeConfig.dark.border}`,
        }}
      >
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            width: '32px',
            height: '32px',
            borderRadius: '8px',
            backgroundColor: platformColor,
          }}
        >
          <Icon size={18} color="white" />
        </div>
        <span
          style={{
            fontSize: '14px',
            fontWeight: 600,
            color: platformColor,
          }}
        >
          {PLATFORM_LABELS[output.platform]}
        </span>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
        {tweets.map((tweet, index) => (
          <div
            key={`tweet-${index}-${tweet.slice(0, 20)}`}
            style={{
              display: 'flex',
              gap: '8px',
              fontSize: '14px',
              lineHeight: '1.5',
            }}
          >
            {isThread && (
              <span
                style={{
                  color: themeConfig.dark.muted,
                  fontWeight: 600,
                  minWidth: '20px',
                }}
              >
                {index + 1}/
              </span>
            )}
            <span style={{ color: themeConfig.dark.foreground }}>{tweet}</span>
          </div>
        ))}
      </div>

      {output.hashtags.length > 0 && (
        <div
          style={{
            marginTop: '16px',
            paddingTop: '12px',
            borderTop: `1px solid ${themeConfig.dark.border}`,
            fontSize: '12px',
            color: themeConfig.dark.primary,
          }}
        >
          {output.hashtags.join(' ')}
        </div>
      )}

      <div
        style={{
          marginTop: '20px',
          paddingTop: '12px',
          borderTop: `1px solid ${themeConfig.dark.border}`,
          display: 'flex',
          alignItems: 'center',
          gap: '6px',
          fontSize: '11px',
          color: themeConfig.dark.muted,
        }}
      >
        <Sprout size={14} />
        <span>Generated by ContentSeed</span>
      </div>
    </div>
  );
}
